Scrapdata/Scrapapp/urls.py
from django.contrib import admin
from django.urls import path

from . import views
app_name = 'urls'
urlpatterns = [
    path('', views.index, name='index'),
]

Scrapdata/Scrapdata/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Scrapapp.urls")),
]

Scrapdata/Scrapapp/models.py
import datetime

from django.conf import settings
from django.db import models

# Create your models here.

# scraperapp/models.py
from django.db import models


class ScrapedData(models.Model):
    college_name = models.CharField(max_length=500, default=True)
    PRN = models.CharField(max_length=200, blank=False, default=True)
    name = models.CharField(max_length=255, default=True)
    TcNo = models.IntegerField(default=True)
    date = models.CharField(max_length=100, default=True)
    reason = models.TextField(default=True)
    mobile = models.IntegerField(max_length=10, default=True)

    def __str__(self):
        return self.name

Scrapdata/Scrapapp/views.py
from django.shortcuts import render
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
import requests
from bs4 import BeautifulSoup
from bs4.element import Comment
from datetime import datetime
from django.utils.dateformat import DateFormat
from django.utils.formats import get_format
from django.utils import formats
# Create your views here.
from .models import ScrapedData


def tag_visible(element):
    if element.parent.name in ['style', 'script', 'head', 'title', 'meta', '[document]']:
        return False
    if isinstance(element, Comment):
        return False
    return True


def index(request):
    if request.method == 'POST':
        url_to_check = request.POST.get('url')
        if url_to_check:
            url_validator = URLValidator()
            try:
                url_validator(url_to_check)
                req = requests.get(url_to_check)
                soup = BeautifulSoup(req.content, "html.parser")
                # for re in soup(["thead"]):
                #     re.extract()
                # for script in soup(["script", "style", "title", "head", "form", 'meta', '[document]']):
                #     script.extract()
                # res = soup.table.text
                # print(res)

                table = soup.find('table')
                rows = table.find_all('tr')
                for row in rows[1:]:  # Skip the header row if present
                    columns = row.find_all('td')
                    college_name = columns[0].text.strip()
                    prn = columns[1].text.strip()
                    std_name = columns[2].text.strip()
                    tcNo = columns[3].text.strip()
                    date = columns[4].text.strip()
                    reason = columns[5].text.strip()
                    phone = columns[6].text.strip()
                    print(date)
                    # df = DateFormat(date)
                    # formatted_datetime = formats.date_format(df, "%d-%m-%Y")
                    # # Df = df.format(get_format('DATE_FORMAT'))
                    # print(formatted_datetime)
                    ScrapedData.objects.create(college_name=college_name, PRN=prn, name=std_name, TcNo=tcNo, date=date, reason=reason, mobile=phone)
                    print(college_name, prn, std_name, tcNo, date, reason, phone)

                # for row in rows:
                #     th = row.find_all('th')
                #     columns = row.find_all('td')
                #     for i in th:
                #         if i.text == "First":
                #             n = len(i)
                #         elif i.text == "Last":
                #             a = len(i)
                #             print(a)
                # print(n, a)
                # for row in rows[1:]:
                #     th = row.find_all('th')
                #     columns = row.find_all('td')
                #     name = columns[a].text.strip()
                #     address = columns[n].text.strip()
                #     print(name, address, a)



            except ValidationError as e:

                error_message = "Invalid URL provided."
                print(error_message)

        else:
            error_message = "Please provide a URL."
            print(error_message)
    return render(request, 'index.html')

Scrapdata/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
   <form action="{% url 'urls:index' %}" method="post">
       {%  csrf_token %}
  <div class="form-group container m-5">
    <label for="url">Enter the url here</label>
    <input type="text" name="url" class="form-control" id="url" placeholder="Enter the URL">
  </div>
   </form>

   <div class="container m-5">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">College</th>
      <th scope="col">PRN</th>
      <th scope="col">Transfer certificate name</th>
      <th scope="col">T.C No</th>
      <th scope="col">Date</th>
      <th scope="col">Reason</th>
      <th scope="col">Mobile No.</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>GH Raisoni</td>
      <td>2019015400339550 FE</td>
      <td>Vishal Rajendra Janjal</td>
      <td>773</td>
      <td>30,07,20</td>
      <td>First Year Computer Scl. Exam form not filled and was absent for whole Academic year 2019-20 admission Cancelled at his own request</td>
      <td>7775945022</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>GH Raisoni</td>
      <td>2019015400161167 FE</td>
      <td>Shaikh Arshad Zahur.</td>
      <td>996</td>
      <td>30-07-2020</td>
      <td>First Year Computer Scl. Exam form not filled and was absent for whole Academic year 2019-20 admission Cancelled at his own request</td>
      <td>9146430410</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>GH Raisoni</td>
      <td>2022100101010663 FE</td>
      <td>Saurabh Rajendra Thakur</td>
      <td>2043</td>
      <td>20,07,2023</td>
      <td>First Year Engg. B.Tech Branch Computer Science First Sem. Examination having Result CGPA 3.44 and Not attempt Second Sem. Exam in Admissin Cancelled as per his own Request.</td>
      <td>7020051163</td>
    </tr>
  </tbody>
</table>
   </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>